#define WORLD_SIZE 		4
#define WORLD_SIZE_1    WORLD_SIZE - 1
#define WORLD_AREA 		WORLD_SIZE*WORLD_SIZE
#define WORLD_VOLUME	WORLD_AREA*WORLD_SIZE

#define WORLD_INIT_POS   0

#define CHUNK_SIZE 		 8
#define CHUNK_SIZE_1     CHUNK_SIZE-1
#define CHUNK_HALF_SIZE  CHUNK_SIZE/2
#define CHUNK_AREA 		 (CHUNK_SIZE * CHUNK_SIZE)
#define CHUNK_VOLUME	 (CHUNK_AREA * CHUNK_SIZE)

#define BLOCK_SIZE 2
#define BLOCK_HALF_SIZE BLOCK_SIZE/2

#define CHUNK_TOTAL_SIZE CHUNK_SIZE * BLOCK_SIZE
#define WORLD_TOTAL_SIZE WORLD_SIZE * CHUNK_TOTAL_SIZE

#define toIndex(x,y,z) ((x) + (y) * WORLD_SIZE + (z) * WORLD_AREA)

#define GRAVITY_VALUE -0.098f * 2.0f

#define AIM_MAX_DISTANCE 20
#define AIM_CAST_STEP   0.1f


extern guVector UP_VECTOR;


